name: CI - Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-and-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installer les dépendances backend
        run: npm ci
        working-directory: ./backend

      - name: Lancer les tests unitaires et d'intégration
        run: npm test
        working-directory: ./backend
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

   e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installer les dépendances backend
        run: npm ci
        working-directory: ./backend

      - name: Installer les dépendances frontend
        run: npm ci
        working-directory: ./frontend

      - name: Installer les navigateurs Playwright
        run: npx playwright install --with-deps chromium
        working-directory: ./backend

      - name: Démarrer le backend
        run: node server.js > backend.log 2>&1 &
        working-directory: ./backend
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - name: Démarrer le frontend
        run: npm start > frontend.log 2>&1 &
        working-directory: ./frontend
        env:
          CI: false

      - name: Attendre les serveurs
        run: |
          npx wait-on http://localhost:3001
          npx wait-on http://localhost:3000

      - name: Lancer les tests end-to-end
        run: npx playwright test
        working-directory: ./backend
        env:
          CI: true
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}